project:
  type: website
  output-dir: docs

website:
  title: "Shamsi's Personal Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true
